# configuracao do bd
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = topicos1
quarkus.datasource.password = 123456
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/topicos1db

# desabilitar o docker 
quarkus.devservices.enabled = false

quarkus.hibernate-orm.database.generation = drop-and-create

quarkus.hibernate-orm.log.sql = true
quarkus.hibernate-orm.log.bind-parameters = true

# Base url para o type em exception
%dev.problem.base-url = http://localhost:8080
%test.problem.base-url = http://localhost:8081
%prod.problem.base-url = https://api.papeis.com

# Configuração do cors
quarkus.http.cors = true

#configuracao jwt
mp.jwt.verify.publickey.location=token/publicKey.pem
mp.jwt.verify.issuer=unitins-jwt
smallrye.jwt.sign.key.location=token/privateKey.pem

quarkus.http.cors.origins=*

# Keycloak OIDC Configuration
quarkus.oidc.enabled=true
%dev.quarkus.oidc.auth-server-url=http://localhost:8180/realms/papeis-artisticos
%dev.quarkus.oidc.client-id=papeis-frontend
%dev.quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET:}
%dev.quarkus.oidc.application-type=web-app
%dev.quarkus.oidc.authentication.cookie-path=/
%dev.quarkus.oidc.token.audience=account

%prod.quarkus.oidc.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL}
%prod.quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID}
%prod.quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}

# Configuração do seaweedfs
seaweedfs.master.url = https://localhost:9333
seaweedfs.request-timeout-ms = 10000

# Dev service do seaweedfs (sobe container automaticamente no perfil dev))
# para desabilitar: %dev.seaweedfs.devservice.enable = false
%dev.seaweedfs.devservice.enabled = true