@startuml Diagram

abstract class Papel {
-Long id 
-Formato formato 
-Textura textura 
}

 
  class Sketchbook{
 -Capa capa
  }
 
 class Bloco {
 -Integer quantidadeFolhas
 }

  
 enum Formato{ 
A5 "Formato A5"
A4 "Formato A4"
A3 "Formato A3"
B5 "Formato B5"
B4 "Formato B4"
B3 "Formato B3"

}
 
 class Rolo {}

 enum Modelo{
 AQUARELA_A4 "Papel para aquarela formato A4" 
 AQUARELA_A3 "Papel para aquarela formato A3"
 QUADRINHO_B4 "Papel para quadrinhos formato B4"
 QUADRINHO_A3 "Papel para quadrinhos formato A3"
 MATERIAIS_SECOS_A4 "Papel para materiais secos" 
 MATERIAIS_SECOS_A5
 }
 
class Capa {
-String material
}

class Textura {
-String descricao
-Integer gramatura
}

Rolo --o Modelo 
Bloco --o Modelo 
Sketchbook --o Modelo 


Textura --* Papel
Formato --* Papel

Sketchbook "1"*--"1" Capa


Papel <|-- Bloco
Papel <|-- Rolo
Papel <|-- Sketchbook
 
class Usuario {
-String nome
-String login
-String senha
}

enum FormaDePagamento{
CARTAO_CREDITO "Cartão de crédito"
CARTAO_DEBITO "Cartão de débito"
BOLETO "Boleto"
PIX "Pix"
}

class Compra {
-FormaDePagamento formaDePagamento
-Papel produto
}

class Administrador {
-String nome
-String login
-String senha
}

Compra *-- Usuario
Compra *-- Papel
Compra *-- FormaDePagamento


@enduml