@startuml Diagram

 abstract class Produto {
 -Long id 
 -Formato formato 
 -Textura textura 
 }

  class PapelAvulso {}

 class TecnicaArtistica {
  -String nome
 }
 
 class Marca {
-String nome
 }
 
 class Sketchbook{
 -Capa capa
 }
 
 class Bloco {
 -Integer quantidadeFolhas
 }

  
class varianteProduto{
  -Long id
  -String formato
  -int gramatura
  -String cor 
  -double preco
}
 class Rolo {
 -Double comprimento
 }

 enum Categoria{
 -String nome
 }
 
 class EspecificacaoTecnica{
 -Double ph
 -Double opacidade
 -Double absorcao
 }
 
class Capa {
-String material
}

enum Textura {
-String descricao
-Integer gramatura
}

Rolo --o Categoria 
Bloco --o Categoria 
Sketchbook --o Categoria 

Textura --* Produto
varianteProduto <-- Produto
varianteProduto <-- itemPedido
EspecificacaoTecnica --> Produto
Marca --o Produto
TecnicaArtistica --> Produto

Sketchbook "1"*--"1" Capa



Produto <|-- Bloco
Produto <|-- Rolo
Produto <|-- Sketchbook
Produto <|-- PapelAvulso
 
class Usuario {
-String nome
-String login
-String senha
}

class Cliente {}

enum FormaDePagamento{
CARTAO_CREDITO "Cartão de crédito"
CARTAO_DEBITO "Cartão de débito"
BOLETO "Boleto"
PIX "Pix"
}

class Compra {
-FormaDePagamento formaDePagamento
-Produto produto
}

class Administrador {}

enum Prioridade{
ALTA ""
BAIXA ""
}

Compra <-- Cliente
Compra *-- Produto
Compra *-- FormaDePagamento

Usuario <|-- Administrador
Usuario <|-- Cliente

@enduml